const projects=[
['project01','Bathroom','bathroom'],['project02','Bathroom Renovation','bathroom'],['project03','Roofing','exterior'],['project04','Bathroom Tile','bathroom'],['project05','Bathroom Finish','bathroom'],['project06','Bathroom Remodel','bathroom'],['project07','Bathroom Remodel','bathroom'],['project08','Walk-In Shower','bathroom'],['project09','Vanity & Bath','bathroom'],['project10','Kitchen Remodel','kitchen'],['project11','Flooring & Tile','flooring'],['project12','Kitchen Remodel','kitchen'],['project13','Exterior Project','exterior'],['project14','Flooring & Tile','flooring'],['project17','Bathroom Remodel','bathroom'],['project23','Exterior / Deck','exterior'],['project25','Flooring','flooring'],['project26','Flooring','flooring'],['project27','Bathroom','bathroom'],['project28','Bathroom Vanity','bathroom'],['project29','Bathroom Tile','bathroom'],['project30','Bathroom Finish','bathroom'],['project31','Bathroom Vanity','bathroom'],['project32','Exterior Construction','exterior'],['project33','Home Remodeling','exterior'],['project34','Flooring','flooring'],['project35','Exterior Project','exterior'],['project36','Kitchen Remodel','kitchen'],['project37','Kitchen Remodel','kitchen']
];
const gallery=document.getElementById('gallery');
function render(filter='all'){gallery.innerHTML=projects.filter(p=>filter==='all'||p[2]===filter).map(p=>`<div class="gallery-card"><img loading="lazy" src="images/${p[0]}.jpg" alt="RF Construction ${p[1]}"><div class="caption">${p[1]}</div></div>`).join('');document.querySelectorAll('.gallery-card').forEach(c=>c.onclick=()=>{document.querySelector('.lightbox img').src=c.querySelector('img').src;document.getElementById('lightbox').classList.add('open')})}
render();
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter)});
document.querySelector('.lightbox button').onclick=()=>document.getElementById('lightbox').classList.remove('open');document.getElementById('lightbox').onclick=e=>{if(e.target.id==='lightbox')e.currentTarget.classList.remove('open')};
document.querySelector('.menu').onclick=()=>document.querySelector('.nav nav').classList.toggle('open');document.querySelectorAll('.nav nav a').forEach(a=>a.onclick=()=>document.querySelector('.nav nav').classList.remove('open'));document.getElementById('year').textContent=new Date().getFullYear();
